language: ruby
rvm:
  - 2.1.1
  - 2.0.0
  - 1.9.3
  - 1.9.2
before_install:
  - sudo add-apt-repository ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential freeglut3-dev libfreeimage-dev libgl1-mesa-dev libopenal-dev libpango1.0-dev libsdl2-ttf2.0-dev libsndfile1-dev libxinerama-dev
